language: node_js
node_js:
- node
- lts/*
- 10
cache: npm
deploy:
  provider: heroku
  api_key:
    secure: MJCnGlAY57fI7I3nbAvRur/685o2yL2DujSzcCcfE0llT8I8dWDY/esa0KYmJtaFCwHxCxes079ZBN7QaBfiq7HbSn8uo4PshSX8ZqJ7Begtdx4O+t7QKN77kw/h/G5C6IQgYigZIA96R0q3MCr24PNpRYeHgm5O75x+8NiFPMQ9sy156HB8+XX7+xDRElfDuvjnOanmtBvKcXhvG6r21zvWxHmUZ09wx8q6ySAc+jStGKx+II2gXxOSqoUWQ6Yi4YgC3bPzgumoEZNMQ9vvBOXyuC4Bbz0cR7zonah2V8++7XJGeKKBjzYTW2RUuSy4jDrMWtMnx59b3hrlMD7NqdElMH/r2Dkw80qMzSHFARfTLINwEJwOxsWsPSk76nLu9jSbUpajRYNJ4rKDnRo0qJLVGMpl+o/+tJm1DwmqLP+wz7da4cRpPIw/1xfR7MYPAcqaNDscpC7uDWICZQoH264uB1bgXyCk4XoCUSsn8MaQiHVxoWB3bugmVfZy1URqTQSLx03CdvRRnk3liBy2NW0P47JVdy1bM4RuLQgWlKJ4T4nvPe2d4FaV6mcaCDrV0ew2Xi7JmcKB01HVHXUk8F4Qy2rMCy4s4CbP0kkcabfdS0k2awdosMegwxLuWUHfcabpukh/7RN/8/RaDHCoJAADXf3DR61jkU21joEeZL8=
